<a href="https://colab.research.google.com/github/Nikolai-N484/Data201_NikolaiN/blob/main/Week2/Week_2_Assignment_Nikolai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 2 - Data Wrangling with pandas**

## **Nikolai Navarro**
---

## Dataset

In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Reben80/Data201/refs/heads/main/Dataset/housing.csv")
df

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[600 rows x 6 columns]

---
## Learning Objectives

By completing this assignment, you should be able to:

- Use pandas equivalents of dplyr verbs:
    - filter() → boolean indexing / .loc[]
    - mutate() → .assign()
    - group_by() → .groupby()
    - summarise() → .agg()
    - arrange() → .sort_values()
- Apply boolean logic correctly using & and |
- Use method chaining for readable, step-by-step transformations
- Create grouped summary tables with multiple statistics
---

## Part A - Core Wrangling (Method Chaining Required)

Using one chained expression, create a summary table that:

1. Keeps only observations where price > 250000
2. Keeps only homes with size > 1000
3. Creates a new variable:
    - price_per_sqft = price / size
4. Groups by neighborhood
5. Computes:
    - mean of price_per_sqft
    - median of price_per_sqft
    - count of homes
6. Sorts the result by mean price_per_sqft (descending)

In [3]:
(df
 .query("price > 250000 and size > 1000")
 .assign(price_per_sqft =lambda d: d["price"] / d["size"])
 .groupby("neighborhood")
 .agg(
     mean_of_price_per_sqft = ("price_per_sqft","mean"),
     median_of_price_per_sqft = ("price_per_sqft","median"),
     count_of_homes = ("listing_id","count")
 )
 .sort_values("mean_of_price_per_sqft", ascending=False)
 )

              mean_of_price_per_sqft  median_of_price_per_sqft  count_of_homes
neighborhood
Downtown                  977.820905               1001.557049              99
Midtown                   921.141446                901.992377              92
Suburb                    861.917078                836.878644             157
Uptown                    860.935608                843.653468              99
Waterfront                849.508891                792.663291              48

---
## Part B - Translation to dplyr

In a Markdown cell, write the equivalent dplyr code that performs the same transformation.

Your R pipeline should include:

filter()\
mutate()\
group_by()\
summarise()\
arrange()


```r
library(dplyr)

df|>
    filter(price > 250000, size > 100)|>
    mutate(price_per_sqft = price / size)|>
    group_by(neighborhood)|>
    summarize(mean_of_price_per_sqft = mean(price_per_sqft),
              median_of_price_per_sqft = median(price_per_sqft),
              count_of_homes = n())|>
    arrange(desc(mean_of_price_per_sqft))
```

Reflection (3-6 sentences)\
Answer:

Which syntax feels clearer for you — pandas chaining or dplyr pipelines?\
What feels similar between them?\
What feels different?

In my last homework assignment I said that I liked to use R more because I was more used to it. This still holds true because I feel like the coding for R looks more clean when compared to python. Especially when you want to (mutate/assign) something mutating in R is very simple while in python I had some trouble having to put brackets and quotations around the columns and add the lambda. Overall both have very similar functions just with different names and they work similarly too. The only function that feels really different from it's R variant would be the .assign function because of what I said before.

---

## Part C - Boolean Logic Debugging
The following code produces an error:

df[df["price"] > 250000 & df["size"] > 1000]

Tasks
Fix the code.\
Explain why the error occurs.\
Rewrite the filter using .query() instead.

In [4]:
df[(df["price"] > 250000) & (df["size"] > 1000)]

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

When using pandas and the & symbol you have to write a parentheses around each condition so each condition is a complete expression. If you don't then the code is read incorrectly by Python due to an operator precedence error.

In [6]:
df.query("price > 250000 and size > 1000")

     listing_id    price         size  bedrooms neighborhood          type
0        100001  1500000  1280.741760       1.0       Suburb     Townhouse
1        100002  1500000  1406.283113       2.0       Uptown  SingleFamily
2        100003  1500000  4146.825713       6.0       Suburb   MultiFamily
3        100004  1500000  3946.599818       6.0       Suburb  SingleFamily
4        100005  1500000  1243.751760       1.0     Downtown   MultiFamily
..          ...      ...          ...       ...          ...           ...
595      100596  1500000  1443.241197       3.0      Midtown         Condo
596      100597  1500000  1083.909714       2.0       Suburb         Condo
597      100598  1500000  1600.126432       1.0       Suburb  SingleFamily
598      100599  1500000  1248.216637       1.0   Waterfront         Condo
599      100600  1500000  1450.981922       NaN       Suburb  SingleFamily

[495 rows x 6 columns]

---
##Part D - Short Concept Questions

Answer briefly (2-4 sentences each):

1. Why must we wrap each condition in parentheses when using & in pandas?\
Because if you don't then the code will be read incorrectly because some operators have higher precedence than others creating either a wrong output or an error.
2. What is the advantage of method chaining over creating many temporary DataFrames?\
Method chaining allows us to write the code in one block making it easier to read as well as eliminating the need of excess variables/dataframes.
3. In .agg(mean_price=("price", "mean")), what does "price" represent? What does "mean" represent?\
Price represents the column of data you want to look at being the price column while mean represents the function being used in this case being calculating the mean of the price column.
4. When you groupby("neighborhood"), why does neighborhood appear on the left (index) in the result table?\
Becauuse pandas makes the column you group by appear on the left side as the index.

---
## Optional Extension (Extra practice)

Create a second summary table grouped by type that reports:
- mean price
- median price
- count of listings

(Use method chaining again.)

In [9]:
(df
 .groupby("type")
 .agg(
     mean_price = ("price", "mean"),
     median_price = ("price", "median"),
     count_of_listings = ("listing_id", "count")
 ))

              mean_price  median_price  count_of_listings
type
Condo          1500000.0     1500000.0                183
MultiFamily    1500000.0     1500000.0                 63
SingleFamily   1500000.0     1500000.0                235
Townhouse      1500000.0     1500000.0                119